#!/usr/bin/with-contenv sh

until pg_isready; do
  sleep 1
done

psql -U postgres -lqt | cut -d \| -f 1 | grep -qw $POSTGRES_DB
if [ $? -ne 0 ]; then
  createdb -U postgres -O postgres $POSTGRES_DB
fi

cd /unms
if [ "$UNMS_LOGGING" = "1" ]; then
  NODE_ENV=production npm start
else
  NODE_ENV=production npm start > /dev/null 2>&1
fi
