#!/usr/bin/with-contenv sh

mkdir -p /config/pg /run/postgresql /var/run/postgresql /usr/share/postgresql/extension/
chown -R postgres:postgres /config/pg /run/postgresql /var/run/postgresql /usr/share/postgresql
chmod 0700 /config/pg

if [ -e /config/pg/postgresql.conf ]; then
  echo "skipping pg configuration due to presenence of config dir"
else
  s6-setuidgid postgres initdb
fi
